import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const read=p=>fs.readFileSync(new URL(p,root),'utf8');
const pkg=JSON.parse(read('package.json'));
const wr=JSON.parse(read('wrangler.jsonc'));
const worker=read('src/index.js');
assert.equal(pkg.private,true);
assert.match(pkg.devDependencies.wrangler,/^4\.146\.0$/);
assert.equal(wr.compatibility_date,'2026-08-23');
assert.equal(wr.d1_databases?.[0]?.binding,'DB');
assert.equal(wr.vars.ALLOWED_ORIGIN,'https://efishell0.github.io');
assert.equal(Object.hasOwn(wr.vars,'SNAPSHOT_GITHUB_TOKEN'),false);
assert.match(worker,/MAX_BODY=/);
assert.match(worker,/new TextDecoder\('utf-8',\{fatal:true\}\)/);
assert.match(worker,/if\(ro&&ro!==allowed\)/);
assert.match(worker,/hasSensitive\(p\)/);
assert.match(worker,/insertResult\?\.meta\?\.changes/);
assert.match(worker,/ctx\?\.waitUntil/);
assert.match(worker,/SNAPSHOT_GITHUB_TOKEN/);
assert.equal(/gh[pousr]_[A-Za-z0-9_]{20,}/.test(JSON.stringify(wr)),false);
console.log('OpenGLESScope Database offline Worker security contract: PASS');
