import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const source=fs.readFileSync(new URL('../assets/app.v070.js',import.meta.url),'utf8');
const a=source.indexOf('const TABS=');
const b=source.indexOf('async function openDetail',a);
if(a<0||b<0)throw new Error('route block missing');
const context={location:{hash:''},state:{view:'reports',detailId:null,detailTab:'summary',compareIds:[]},META:{reports:1,opengles:1,egl:1,extensions:1,limits:1,formats:1,precision:1,eglconfigs:1,display:1,diagnostics:1,compare:1},decodeURIComponent};
vm.createContext(context);
vm.runInContext(`${source.slice(a,b)};this.routeReportHash=routeReportHash;this.routeCompareHash=routeCompareHash;this.applyHashRoute=applyHashRoute`,context);
const A='a'.repeat(64),B='b'.repeat(64);
assert.equal(context.routeReportHash(A,'summary'),`#reports/${A}/Overview`);
assert.equal(context.routeReportHash(A,'display'),`#reports/${A}/Display-HDR`);
assert.equal(context.routeCompareHash(A,B),`#compare/${A}/${B}`);
context.location.hash=`#reports/${A}`;assert.equal(context.applyHashRoute(),true);assert.equal(context.state.detailId,A);assert.equal(context.state.detailTab,'summary');
context.location.hash=`#reports/${A}/Limits`;assert.equal(context.applyHashRoute(),true);assert.equal(context.state.detailTab,'limits');
context.location.hash=`#reports/${A}/Nope`;assert.equal(context.applyHashRoute(),false);
context.location.hash=`#reports/${'A'.repeat(64)}/Overview`;assert.equal(context.applyHashRoute(),false);
context.location.hash=`#compare/${A}/${B}`;assert.equal(context.applyHashRoute(),true);assert.deepEqual(Array.from(context.state.compareIds),[A,B]);
context.location.hash='#opengles';assert.equal(context.applyHashRoute(),true);assert.equal(context.state.view,'opengles');
console.log('OpenGLESScope Database route tests: ALL PASS');
