import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const app=fs.readFileSync(new URL('../assets/app.v2005.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/site.v2005.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const need=(hay,needle,label=needle)=>assert.equal(hay.includes(needle),true,`missing ${label}`);
for(const token of ['site.v2005.css','app.v2005.js','config.js?v=2005'])need(html,token);
const expected='bd5957461701439a7655c652b4e560cb84b7cc0163f202a257e019c2c468181b';
assert.equal(createHash('sha256').update(css.slice(0,266459)).digest('hex'),expected,'the VulkanScope shared stylesheet must be FIRST and byte-identical');
assert.equal(css.includes('/'+'* GL/EGL-only existing components'),false,'duplicated legacy shared style layer forbidden');
for(const token of ['.topbar-inner','.brand img','.nav-shell','.nav-icon','.hero-v127-grid','.hero-command-deck','.settings-drawer','.settings-category-nav','.cards','.custom-select','.page-scroll-controls','.viewport-scrollbar','.reports-table','.detail-back-button','.compare-picker','.compare-diff-input','.table-scroll-thumb','@media(max-width:760px)'])need(css,token,`reference shape ${token}`);
for(const token of ['class="hero-v127-brand-heading">OpenGL® ES™ Hardware Database</h1>','class="filter-family report-toolbar-family"','<span>Sort</span>','<span>Per page</span>','<svg class="nav-icon"','<div id="compareFilters" class="subfilters"></div>','filterHost.innerHTML=selectControl(\'compareSection\',\'Section\'','textControl(\'compareFieldSearch\',\'Field search\'','<button id="shareCompare" class="page-button compare-share-button"'])need(token.includes('class="hero-v127-brand-heading"')?html:app,token,`shared component hierarchy ${token}`);
assert.equal(html.includes('<div class="filter-bar-heading">'),false,'legacy extra filter header forbidden');
assert.equal(html.includes('class="live-strip" hidden'),true,'live status must not distort reference hero');
assert.equal(css.includes('@import'),false,'remote CSS imports forbidden');
assert.equal(/https?:\/\//.test(css),false,'remote CSS resources forbidden');
console.log('OpenGLESScope Database 2.0.5 canonical shared UI, no legacy overrides, and component structure: ALL PASS');
