import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const source=fs.readFileSync(new URL('../assets/app.v3002.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/site.v3002.css',import.meta.url),'utf8');
const extract=name=>{const a=source.indexOf(`function ${name}`);if(a<0)throw new Error(`missing ${name}`);const start=source.indexOf('{',a);let depth=0,quote=null,escape=false;for(let i=start;i<source.length;i++){const c=source[i];if(quote){if(escape)escape=false;else if(c==='\\')escape=true;else if(c===quote)quote=null;continue}if(c==='"'||c==="'"||c==='`'){quote=c;continue}if(c==='{')depth++;else if(c==='}'&&--depth===0)return source.slice(a,i+1)}throw new Error(`unterminated ${name}`)};
const context={Map,Object,Array,String,JSON,normalized:p=>p.technicalReport||{},diagnosticIndex:n=>new Map((n.diagnostics||[]).map(x=>[x.name,x])),reportPlatform:p=>p.application?.applicationAbi||'Unknown',reportSupportedAbis:p=>(p.application?.supportedDeviceAbis||[]).join(', '),precisionDiagKey:k=>k.replace(' / ','/')} ;
vm.createContext(context);
vm.runInContext(`${extract('reportMap')};this.reportMap=reportMap`,context);
const payload={application:{version:'0.7.2',versionCode:702,applicationAbi:'arm64-v8a',supportedDeviceAbis:['arm64-v8a']},device:{manufacturer:'X',model:'Y',product:'Z',androidRelease:'16',sdk:36},collection:{status:'Complete',complete:true,source:'runtime'},driver:{mode:'System',version:'1'},gpu:{name:'GPU',vendor:'Vendor'},opengles:{version:'OpenGL ES 3.2',major:3,minor:2,glslVersion:'OpenGL ES GLSL ES 3.20'},egl:{vendor:'EGLV',version:'1.5',initializedVersion:'1.5',clientApis:'OpenGL_ES'},technicalReport:{schemaVersion:2,eglRuntime:{boundApi:'EGL_OPENGL_ES_API (0x30A0)',configId:1,clientType:'EGL_OPENGL_ES_API (0x30A0)',clientVersion:3,renderBuffer:'EGL_BACK_BUFFER (0x3084)',currentContext:true,currentDisplay:true,currentDrawSurface:true,currentReadSurface:true,surfaceWidth:1,surfaceHeight:1,surfaceRenderBuffer:'EGL_BACK_BUFFER (0x3084)',surfaceSwapBehavior:'EGL_BUFFER_DESTROYED (0x3095)',surfaceTextureFormat:'EGL_NO_TEXTURE (0x305C)',surfaceTextureTarget:'EGL_NO_TEXTURE (0x305C)',surfaceMipmapTexture:0,surfaceMipmapLevel:0,surfaceMultisampleResolve:null,unavailableAttributes:[{name:'EGL_MULTISAMPLE_RESOLVE',error:'EGL_BAD_ATTRIBUTE (0x3004)'}]},limits:[{name:'GL_MAX_TEXTURE_SIZE',value:'16384'}],extensions:['GL_EXT_test'],eglExtensions:[],eglClientExtensions:[],compressedFormats:[],shaderBinaryFormats:[],programBinaryFormats:[],precision:[],diagnostics:[{name:'GL_MAX_TEXTURE_SIZE',status:'Available',detail:'ok'},{name:'GL_FAKE',status:'Unavailable',detail:'GL error'}],eglConfigs:[],display:{wideColor:true,hdrTypes:[]}}};
const map=context.reportMap(payload);
assert.equal(map.get('LimitsGL_MAX_TEXTURE_SIZE').status,'Available');
assert.equal(map.get('LimitsGL_MAX_TEXTURE_SIZE').showStatus,true);
assert.equal(map.get('DiagnosticsGL_FAKE').status,'Unavailable');
assert.equal(map.get('OpenGL ES extensionsGL_EXT_test').value,'Reported');
assert.equal(map.get('Display & HDRwideColor').status,'Supported');
assert.equal(map.get('Display & HDRhdrTypes').status,'Unavailable');
assert.equal(map.get('EGL runtimeboundApi').value,'EGL_OPENGL_ES_API (0x30A0)');
assert.equal(map.get('EGL runtime unavailable attributesEGL_MULTISAMPLE_RESOLVE').status,'Unavailable');
for(const token of ['Common evidence only','Cross-producer comparison','One-sided fields','Common fields','Visible differences','Visible sections','Unknown / Not reported','compareSection','compareFieldSearch','Share comparison link','routeCompareUrl'])assert.equal(source.includes(token),true,`missing ${token}`);
assert.equal(source.includes("av!==bv||ac!==bc"),true,'cross-producer detection must include versionCode');
assert.equal(source.includes("commonOnly?commonKeys:technicalUniverse"),true,'common evidence filtering contract');
assert.equal(source.includes("if(!x)return `${badge('Unknown','unknown')} <span class=\"muted\">Not reported</span>`"),true,'missing evidence presentation');

for(const token of ['compare-diff-toggle','compare-diff-input','compare-diff-check','#contentView[data-main-view="compare"] .compare-picker','#compareFilters','.subfilter-control','.compare-share-button'])assert.equal(css.includes(token),true,`missing compare layout CSS ${token}`);
assert.equal(css.includes('.compare-picker label:not(.compare-diff-toggle)'),true,'generic compare label rule must exclude boolean toggles');
assert.equal(css.includes('.compare-picker input:not(.compare-diff-input)'),true,'generic compare input rule must exclude hidden checkbox inputs');
assert.equal(css.includes('.compare-diff-input{position:absolute'),true,'compare checkbox must use dedicated visually-hidden input geometry');
console.log('OpenGLESScope Database compare contract tests: ALL PASS');
