import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const app=readFileSync(new URL('../assets/app.v3026.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../assets/site.v3026.css',import.meta.url),'utf8');
const enhancement=app.slice(app.indexOf('function enhanceSearchClear('),app.indexOf('const searchEnhancementObserver='));
assert.ok(enhancement.includes("input.parentElement?.querySelector(':scope > .search-clear-button')"),'existing clear must prevent enhancement');
assert.equal((app.match(/id="registrySearchClear"/g)||[]).length,1,'encyclopedia authors one clear');
assert.ok(app.includes("clear=$('#registrySearchClear')"),"clear handler must be retained");
assert.match(css,/input\[type="search"\]::-webkit-search-cancel-button\{[^}]*display:none/);
console.log('3.0.26 encyclopedia single-X source contract: PASS');
