import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const app=fs.readFileSync(new URL('../assets/app.v3006.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/site.v3006.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const need=(hay,needle,label=needle)=>assert.equal(hay.includes(needle),true,`missing ${label}`);
for(const token of ['site.v3006.css','app.v3006.js','config.js?v=3006'])need(html,token);
const expected=fs.readFileSync(new URL('../rules/SHARED_UI_BASE_SHA256.txt',import.meta.url),'utf8').trim().split(/\r?\n/)[1];
const canonicalBase=css.slice(0,css.indexOf('\n\n.not-applicable'));
assert.equal(createHash('sha256').update(canonicalBase).digest('hex'),expected,'VulkanScope base with OpenGLESScope official color mapping must be FIRST and SHA-pinned');
assert.equal(css.includes('/'+'* GL/EGL-only existing components'),false,'duplicated legacy shared style layer forbidden');
for(const token of ['.topbar-inner','.brand img','.nav-shell','.nav-icon','.hero-v127-grid','.hero-command-deck','.settings-drawer','.settings-category-nav','.cards','.custom-select','.page-scroll-controls','.viewport-scrollbar','.reports-table','.detail-back-button','.compare-picker','.compare-diff-input','.table-scroll-thumb','@media(max-width:760px)'])need(css,token,`reference shape ${token}`);
for(const token of ['class="hero-v127-brand-heading">OpenGL® ES™ Hardware Database</h1>','class="filter-family report-toolbar-family"','<span>Sort</span>','<span>Per page</span>','<svg class="nav-icon"','<div id="compareFilters" class="compare-filter-panel subfilters"></div>','selectControl(\'compareSection\',\'Section\'','textControl(\'compareFieldSearch\',\'Field search\'','<button id="shareCompare" class="compare-share-button"'])need(token.includes('class="hero-v127-brand-heading"')?html:app,token,`shared component hierarchy ${token}`);
assert.equal(html.includes('<div class="filter-bar-heading">'),false,'legacy extra filter header forbidden');
assert.equal(html.includes('class="live-strip" hidden'),true,'live status must not distort reference hero');
assert.equal(css.includes('@import'),false,'remote CSS imports forbidden');
assert.equal(/https?:\/\//.test(css),false,'remote CSS resources forbidden');
console.log('OpenGLESScope Database 3.0.6 canonical shared UI, no legacy overrides, and component structure: ALL PASS');
