import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const read=name=>fs.readFileSync(new URL(name,root),'utf8');
const app=read('assets/app.v3030.js'),ux=read('assets/experience.v3030.js'),style=read('assets/site.v3030.css'),boot=read('assets/release-bootstrap.v3030.js');
assert.ok(app.includes('const routeScrollPositions=new Map()'));
assert.ok(app.includes("history.scrollRestoration='manual'"));
assert.ok(app.includes('rememberRouteScroll(detailReturnRoute);history.pushState({report:id}'));
assert.ok(app.includes('detailReturnScroll=Math.max(0,window.scrollY||0)'));
assert.ok(app.includes('routeScrollPositions.set(returnTo,target)'));
assert.ok(app.includes('renderDetail(p,restore);syncDetailBackTop(false)' ));
assert.ok(app.includes('render();restoreRouteScroll(location.hash)'));
assert.ok(app.includes('suppressReportNavigationUntil=performance.now()+400'));
assert.ok(app.includes('const shouldSuppressReportNavigation='));
assert.ok(app.includes('shouldSuppressReportNavigation(e)'));
assert.ok(app.includes('id="downloadReportJson"')&&!app.includes('id="downloadRawReport"'));
assert.ok(app.includes('id="downloadRawTabReport"')&&app.includes('class="raw-report-toolbar"'));
assert.ok(app.includes('new TextEncoder().encode(raw).byteLength'));
assert.ok(app.includes('String(p.reportText??\'\')'));
assert.ok(app.includes('?compact=1&_download=${Date.now()}'));
assert.ok(app.includes("String(payload.id)!==String(p.id)"));
assert.ok(app.includes("type:'application/json;charset=utf-8'"));
assert.ok(app.includes("'text/plain;charset=utf-8',rawReportFileName(p)"));
assert.ok(style.includes('.detail-action-button.downloaded')&&style.includes('.detail-action-button.download-failed'));
assert.ok(style.includes('.detail-action-button.copied')&&style.includes('.raw-report-toolbar'));
assert.ok(ux.includes('publicationTransition=true'));
assert.ok(ux.includes("if(head?.databaseReleaseVersion!==VERSION){if(!semver(head?.databaseReleaseVersion))throw Error('Invalid Worker release version');publicationTransition=true;banner('checking');void releases();return}"));
assert.ok(ux.includes("async function releases(){if(releaseBusy||!reachable()||document.hidden)return;"));
assert.ok(!ux.includes('async function releases(){if(!ready||releaseBusy'));
assert.ok(ux.includes('published(m))navigatePublishedRelease(m.databaseVersion)'));
assert.ok(ux.includes('i===0?524288:i===2?1048576:2097152'));
assert.ok(ux.includes("document.addEventListener('openglesscope:release-transition'"));
assert.ok(boot.includes('for(const delay of EARLY_RETRIES)'));
assert.ok(boot.includes('release-check-pending'));
console.log('OpenGLESScope Database 3.0.30 export, route-scroll, selection, staged-publication and dialog interaction contracts: ALL PASS');
