import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../assets/app.v3030.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/site.v3030.css',import.meta.url),'utf8');
for(const id of ['vendorFilter','gpuFilter','apiFilter','eglFilter','driverModeFilter','driverVersionFilter','androidFilter','deviceModelFilter','abiFilter','appVersionFilter','extensionTokenFilter','submissionAgeFilter','resolutionFilter','refreshRateFilter','wideColorFilter','hdrStateFilter','hdrTypeFilter','clearFilters'])assert.equal(html.includes(`id="${id}"`),true,`missing cohort filter ${id}`);
for(const token of ['statisticsSliceLimit','statisticsExtensionScope','statisticsExtensionNamespace','statisticsExtensionMinShare','statisticsExtensionSearch','Extension enumeration ranking','Submission timeline','data-stat-filter','not device-population or market-share estimates'])assert.equal(source.includes(token),true,`missing Statistics token ${token}`);
for(const token of ['extensionRowSearch','limitRowSearch','formatRowSearch','precisionRowSearch'])assert.equal(source.includes(token),true,`missing view search ${token}`);
assert.equal(source.includes("state.view==='display'")&&source.includes("FILTER_APPLICABILITY_GL"),true,'Display/HDR isolation missing');
for(const token of ['distribution-grid','donut-chart','donut-segment','chart-filter-button'])assert.equal(css.includes(token),true,`missing local chart style ${token}`);
assert.equal(css.includes('@import'),false,'remote/imported CSS forbidden');
assert.equal(/https?:\/\//.test(css),false,'remote CSS resource forbidden');
const a=source.indexOf('function compactDistribution');
const b=source.indexOf('function donut',a);
const c=source.indexOf('function extensionNamespace');
const d=source.indexOf('async function renderStatistics',c);
assert.ok(a>=0&&b>a&&c>=0&&d>c,'statistics helper blocks missing');
const context={Math,Number,String};vm.createContext(context);vm.runInContext(`${source.slice(a,b)};${source.slice(c,d)};this.compactDistribution=compactDistribution;this.extensionNamespace=extensionNamespace`,context);
const compact=context.compactDistribution([{count:5},{count:4},{count:3},{count:2},{count:1}],3);
assert.equal(compact.length,3);assert.equal(compact[2].other,true);assert.equal(compact[2].count,6);
assert.equal(context.extensionNamespace('GL_EXT_texture_filter_anisotropic'),'GL_EXT');
assert.equal(context.extensionNamespace('EGL_ANDROID_recordable'),'EGL_ANDROID');
assert.equal(context.extensionNamespace('UNKNOWN_TOKEN'),'Other');
console.log('OpenGLESScope Database Statistics/filter tests: ALL PASS');
