import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync(new URL('../assets/app.v074.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../assets/site.v074.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const need=(hay,needle,label=needle)=>assert.equal(hay.includes(needle),true,`missing ${label}`);
for(const token of ['site.v074.css','app.v074.js','config.js?v=074'])need(html,token);
for(const token of ['.brand img{width:min(226px,36vw)}','.nav-shell{margin-left:34px;gap:6px}','.nav-icon{width:15px;height:15px;flex:0 0 15px;opacity:.88}','.hero-heading-row{gap:28px}','.cards{grid-template-columns:repeat(auto-fit,minmax(290px,1fr))}'])need(css,token,`shared presentation geometry ${token}`);
for(const token of ['.custom-select{min-width:190px;max-width:none;flex:1}','border-radius:13px;gap:12px;box-shadow:0 8px 24px rgba(0,0,0,.14)','width:17px;height:17px;flex:0 0 17px','transform:rotate(180deg)','visibility:hidden;pointer-events:none','visibility:visible;pointer-events:auto'])need(css,token,`custom-select parity ${token}`);
for(const token of ['.filter-clear-button[hidden],#clearFilters[hidden]{display:none!important}','clear.hidden=!(active||String(state.query||\'\').trim())'])need(token.includes('clear.hidden')?app:css,token,'clear-filter state contract');
for(const token of ['#contentView[data-main-view="compare"] .compare-picker{align-items:center;gap:7px;margin:0 0 12px;max-width:760px}','#compareFilters{margin:0 0 12px;max-width:760px;width:100%}','.subfilters{display:flex;gap:8px;flex-wrap:wrap;align-items:flex-end;margin:0 0 14px;width:auto}','.subfilter-control{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:5px!important;min-width:150px;width:auto!important;flex:0 1 230px}','.compare-sections{display:grid;gap:18px;margin-top:18px}','.compare-section{border:1px solid var(--line);border-radius:18px;background:var(--panel);overflow:hidden;margin:0}'])need(css,token,`Compare layout parity ${token}`);
for(const token of ['<div id="compareFilters" class="subfilters"></div>','filterHost.innerHTML=selectControl(\'compareSection\',\'Section\'','textControl(\'compareFieldSearch\',\'Field search\'','<button id="shareCompare" class="page-button compare-share-button"'])need(app,token,`Compare hierarchy ${token}`);
for(const token of ['@media(max-width:760px){','.subfilters{display:grid;grid-template-columns:1fr 1fr;align-items:end;width:100%}','#contentView[data-main-view="compare"] .compare-picker{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));max-width:none;gap:6px}','@media(max-width:430px){.subfilters{grid-template-columns:1fr}'])need(css,token,`responsive parity ${token}`);
for(const token of ['.table-scroll-shell{margin:0 0 4px}','.table-scroll-controls{height:38px;padding:7px 8px 0}','.table-scroll-button{flex:0 0 30px}','.table-scroll-track{height:12px;min-width:0}','.table-scroll-thumb{height:6px;min-width:34px}'])need(css,token,`table scroll parity ${token}`);
assert.equal(css.includes('@import'),false,'remote CSS imports forbidden');
assert.equal(/https?:\/\//.test(css),false,'remote CSS resources forbidden');
console.log('OpenGLESScope Database shared UI parity tests: ALL PASS');
